global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-microsoft-sql
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
#  master-old:
#    parameter_input: SQL_AlwaysOn_Master.json
#    regions:
#      - ap-northeast-1
#      - ap-northeast-2
#      - ap-south-1
#      - ap-southeast-1
#      - ap-southeast-2
#      - eu-central-1
#      - eu-west-1
#      # - sa-east-1 Unsupported only in CI due to GetAZs on ref acct
#      - us-east-1
#      - us-east-2
#      - us-west-1
#      - us-west-2
#    template_file: SQL_AlwaysOn_Master.template
  defaults:
    parameter_input: sql-master-defaults.json
    template_file: sql-master.template
  sql-2016:
    parameter_input: sql-master-sql-2016.json
    template_file: sql-master.template
  ebs-io1:
    parameter_input: sql-master-ebs-io1.json
    template_file: sql-master.template
  3rdaz-witness:
    parameter_input: sql-master-3rdaz-witness.json
    regions:
      - ap-southeast-2
      - eu-west-1
      - us-east-1
      - us-west-2
    template_file: sql-master.template
  3rdaz-full:
    parameter_input: sql-master-3rdaz-full.json
    regions:
      - ap-southeast-2
      - eu-west-1
      - us-east-1
      - us-west-2
    template_file: sql-master.template
  license-included:
    parameter_input: sql-master-license-included.json
    regions:
      - eu-west-1
      - us-east-1
      - us-west-2
    template_file: sql-master.template
